name: Trigger Deploy

on:
  workflow_run:
    workflows: ["Generate game info"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST \
          -H "Authorization: Bearer ${{secrets.PERSONAL_ACCESS_TOKEN}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/n3evin/${{secrets.SERVER_REPOISTORY}}/actions/workflows/deploy.yml/dispatches \
          -d '{"ref": "master"}'